tree_species = {
    "Abies balsamea": "Balsam Fir",
    "Abies concolor": "White Fir",
    "Abies fraseri": "Fraser Fir",
    "Abies spp.": "Fir species",
    "Acer campestre": "Hedge Maple",
    "Acer ginnala": "Amur Maple",
    "Acer grandidentatum": "Bigtooth Maple",
    "Acer negundo": "Boxelder",
    "Acer nigrum": "Black Maple",
    "Acer palmatum": "Japanese Maple",
    "Acer pensylvanicum": "Striped Maple",
    "Acer platanoides": "Norway Maple",
    "Acer pseudosieboldianum": "Korean Maple",
    "Acer rubrum": "Red Maple",
    "Acer saccharinum": "Silver Maple",
    "Acer saccharum": "Sugar Maple",
    "Acer spp.": "Maple species",
    "Acer tegmentosum": "Manchu Stripe Maple",
    "Acer triflorum": "Three-flowered Maple",
    "Acer truncatum": "Shantung Maple",
    "Acer x Hipzam": "Highland Park Maple",
    "Acer x freemanii": "Freeman Maple",
    "Aesculus flava": "Yellow Buckeye",
    "Aesculus glabra": "Ohio Buckeye",
    "Aesculus hippocastanum": "Horse Chestnut",
    "Aesculus spp.": "Buckeye/Horse Chestnut species",
    "Aesculus x Bergeson": "Bergeson Buckeye",
    "Aesculus x Homestead": "Homestead Buckeye",
    "Aesculus x arnoldiana": "Arnold Buckeye",
    "Aesculus x carnea": "Red Horse Chestnut",
    "Alnus glutinosa": "European Alder",
    "Alnus hirsuta": "Manchurian Alder",
    "Alnus spaethii": "Spaeth's Alder",
    "Alnus spp.": "Alder species",
    "Amelanchier alnifolia": "Saskatoon Serviceberry",
    "Amelanchier arborea": "Downy Serviceberry",
    "Amelanchier canadensis": "Canadian Serviceberry",
    "Amelanchier laevis": "Allegheny Serviceberry",
    "Amelanchier spp.": "Serviceberry species",
    "Amelanchier x grandiflora": "Apple Serviceberry",
    "Betula alleghaniensis": "Yellow Birch",
    "Betula lenta": "Sweet Birch",
    "Betula nigra": "River Birch",
    "Betula papyrifera": "Paper Birch",
    "Betula pendula": "European White Birch",
    "Betula platyphylla": "Asian White Birch",
    "Betula populifolia": "Gray Birch",
    "Betula spp.": "Birch species",
    "Carpinus betulus": "European Hornbeam",
    "Carpinus caroliniana": "American Hornbeam",
    "Carpinus spp.": "Hornbeam species",
    "Carya cordiformis": "Bitternut Hickory",
    "Carya glabra": "Pignut Hickory",
    "Carya illinoisensis": "Pecan",
    "Carya ovata": "Shagbark Hickory",
    "Carya spp.": "Hickory species",
    "Castanea dentata": "American Chestnut",
    "Castanea mollissima": "Chinese Chestnut",
    "Catalpa bungei": "Manchurian Catalpa",
    "Catalpa ovata": "Chinese Catalpa",
    "Catalpa speciosa": "Northern Catalpa",
    "Catalpa spp.": "Catalpa species",
    "Catalpa x erubescens": "Hybrid Catalpa",
    "Celtis occidentalis": "Common Hackberry",
    "Cercidiphyllum japonicum": "Katsura Tree",
    "Cercis canadensis": "Eastern Redbud",
    "Cercis spp.": "Redbud species",
    "Chamaecyparis spp.": "False Cypress species",
    "Chionanthus spp.": "Fringetree species",
    "Cladrastis kentukea": "Yellowwood",
    "Cornus alternifolia": "Pagoda Dogwood",
    "Cornus racemosa": "Gray Dogwood",
    "Cornus sericea": "Red-osier Dogwood",
    "Cornus spp.": "Dogwood species",
    "Corylus colurna": "Turkish Filbert",
    "Cotinus coggygria": "European Smoketree",
    "Crataegus crus-galli": "Cockspur Hawthorn",
    "Crataegus phaenopyrum": "Washington Hawthorn",
    "Crataegus punctata": "Dotted Hawthorn",
    "Crataegus spp.": "Hawthorn species",
    "Crataegus viridis": "Green Hawthorn",
    "Crataegus x mordenensis": "Morden Hawthorn",
    "Elaeagnus angustifolia": "Russian Olive",
    "Eucommia ulmoides": "Hardy Rubber Tree",
    "Euonymus atropurpureus": "Eastern Wahoo",
    "Fagus grandifolia": "American Beech",
    "Fagus spp.": "Beech species",
    "Fagus sylvatica": "European Beech",
    "Fraxinus americana": "White Ash",
    "Fraxinus mandshurica": "Manchurian Ash",
    "Fraxinus nigra": "Black Ash",
    "Fraxinus pennsylvanica": "Green Ash",
    "Fraxinus spp.": "Ash species",
    "Ginkgo biloba": "Ginkgo",
    "Gleditsia triacanthos": "Honey Locust",
    "Gymnocladus dioicus": "Kentucky Coffeetree",
    "Halesia caroliniana": "Carolina Silverbell",
    "Hamamelis virginiana": "American Witch-hazel",
    "Hemiptelea davidii": "David Elm-zelkova",
    "Juglans cinerea": "Butternut",
    "Juglans nigra": "Black Walnut",
    "Juglans regia": "English Walnut",
    "Juglans spp.": "Walnut species",
    "Juniperus communis": "Common Juniper",
    "Juniperus horizontalis": "Creeping Juniper",
    "Juniperus scopulorum": "Rocky Mountain Juniper",
    "Juniperus spp.": "Juniper species",
    "Juniperus virginiana": "Eastern Redcedar",
    "Koelreuteria paniculata": "Goldenrain Tree",
    "Larix decidua": "European Larch",
    "Larix kaempferi": "Japanese Larch",
    "Larix laricina": "Tamarack",
    "Larix spp.": "Larch species",
    "Liquidambar styraciflua": "American Sweetgum",
    "Liriodendron tulipifera": "Tulip Tree",
    "Maackia amurensis": "Amur Maackia",
    "Maackia spp.": "Maackia species",
    "Maclura pomifera": "Osage Orange",
    "Magnolia acuminata": "Cucumber Tree",
    "Magnolia spp.": "Magnolia species",
    "Magnolia stellata": "Star Magnolia",
    "Magnolia virginiana": "Sweetbay Magnolia",
    "Magnolia x Ann": "Ann Magnolia",
    "Magnolia x Jane": "Jane Magnolia",
    "Magnolia x loebneri": "Loebner Magnolia",
    "Malus domestica": "Orchard Apple",
    "Malus ioensis": "Prairie Crabapple",
    "Malus spp.": "Crabapple species",
    "Malus x Adams": "Adams Crabapple",
    "Malus x Centennial": "Centennial Crabapple",
    "Malus x Chestnut": "Chestnut Crabapple",
    "Malus x Dolgo": "Dolgo Crabapple",
    "Malus x Donald Wyman": "Donald Wyman Crabapple",
    "Malus x Freedom": "Freedom Apple",
    "Malus x Honeycrisp": "Honeycrisp Apple",
    "Malus x Indian Summer": "Indian Summer Crabapple",
    "Malus x Jewelcole": "Red Jewel Crabapple",
    "Malus x Liberty": "Liberty Apple",
    "Malus x Novamac": "Novamac Apple",
    "Malus x Pink Spires": "Pink Spires Crabapple",
    "Malus x Prairie Rose": "Prairie Rose Crabapple",
    "Malus x Prairifire": "Prairifire Crabapple",
    "Malus x Radiant": "Radiant Crabapple",
    "Malus x Red Splendor": "Red Splendor Crabapple",
    "Malus x Royal Raindrops": "Royal Raindrops Crabapple",
    "Malus x Snowdrift": "Snowdrift Crabapple",
    "Malus x Spring Snow": "Spring Snow Crabapple",
    "Malus x Zestar": "Zestar Apple",
    "Metasequoia glyptostroboides": "Dawn Redwood",
    "Microbiota decussata": "Russian Cypress",
    "Morus alba": "White Mulberry",
    "Morus rubra": "Red Mulberry",
    "Morus spp.": "Mulberry species",
    "Nyssa sylvatica": "Black Tupelo",
    "Olneya tesota": "Desert Ironwood",
    "Ostrya virginiana": "American Hophornbeam",
    "Phellodendron amurense": "Amur Corktree",
    "Phellodendron lavallei": "Lavalle Corktree",
    "Phellodendron spp.": "Corktree species",
    "Physocarpus opulifolius": "Common Ninebark",
    "Picea abies": "Norway Spruce",
    "Picea glauca": "White Spruce",
    "Picea mariana": "Black Spruce",
    "Picea pungens": "Colorado Blue Spruce",
    "Picea spp.": "Spruce species",
    "Pinus aristata": "Bristlecone Pine",
    "Pinus banksiana": "Jack Pine",
    "Pinus cembra": "Swiss Stone Pine",
    "Pinus contorta": "Lodgepole Pine",
    "Pinus flexilis": "Limber Pine",
    "Pinus heldreichii": "Bosnian Pine",
    "Pinus mugo": "Mugo Pine",
    "Pinus nigra": "Austrian Pine",
    "Pinus ponderosa": "Ponderosa Pine",
    "Pinus resinosa": "Red Pine",
    "Pinus spp.": "Pine species",
    "Pinus strobus": "Eastern White Pine",
    "Pinus sylvestris": "Scots Pine",
    "Platanus occidentalis": "American Sycamore",
    "Platanus spp.": "Sycamore species",
    "Platanus x acerifolia": "London Planetree",
    "Populus alba": "White Poplar",
    "Populus housesamifera": "Balsam Poplar",
    "Populus deltoides": "Eastern Cottonwood",
    "Populus grandidentata": "Bigtooth Aspen",
    "Populus nigra": "Lombardy Poplar",
    "Populus spp.": "Poplar/Aspen species",
    "Populus tremuloides": "Quaking Aspen",
    "Prunus americana": "American Plum",
    "Prunus armeniaca": "Apricot",
    "Prunus cerasifera": "Cherry Plum",
    "Prunus cerasus": "Sour Cherry",
    "Prunus domestica": "Common Plum",
    "Prunus maackii": "Amur Chokecherry",
    "Prunus nigra": "Canada Plum",
    "Prunus padus": "European Bird Cherry",
    "Prunus persica": "Peach",
    "Prunus sargentii": "Sargent Cherry",
    "Prunus serotina": "Black Cherry",
    "Prunus spp.": "Cherry/Plum species",
    "Prunus virginiana": "Chokecherry",
    "Prunus x Alderman": "Alderman Plum",
    "Prunus x Eubank": "Pink Cascade Cherry",
    "Prunus x Lydecker": "Black Ice Plum",
    "Prunus x North Star": "North Star Cherry",
    "Prunus x Spring Wonder": "Spring Wonder Cherry",
    "Prunus x Superior": "Superior Plum",
    "Prunus x Toka": "Toka Plum",
    "Pseudotsuga menziesii": "Douglas-fir",
    "Ptelea trifoliata": "Common Hoptree",
    "Pyrus calleryana": "Callery Pear",
    "Pyrus communis": "Common Pear",
    "Pyrus spp.": "Pear species",
    "Pyrus ussuriensis": "Ussurian Pear",
    "Pyrus x Parker": "Parker Pear",
    "Pyrus x Patten": "Patten Pear",
    "Pyrus x Summercrisp": "Summercrisp Pear",
    "Pyrus x triploida": "Triploid Pear",
    "Qercus x macdanielli": "Heritage Oak",
    "Quercus acutissima": "Sawtooth Oak",
    "Quercus alba": "White Oak",
    "Quercus bicolor": "Swamp White Oak",
    "Quercus ellipsoidalis": "Northern Pin Oak",
    "Quercus imbricaria": "Shingle Oak",
    "Quercus macrocarpa": "Bur Oak",
    "Quercus muehlenbergii": "Chinquapin Oak",
    "Quercus palustris": "Pin Oak",
    "Quercus prinus": "Chestnut Oak",
    "Quercus robur": "English Oak",
    "Quercus rubra": "Northern Red Oak",
    "Quercus spp.": "Oak species",
    "Quercus velutina": "Black Oak",
    "Quercus x Atwood": "Atwood Oak",
    "Quercus x Crimschmidt": "Crimson Spire Oak",
    "Quercus x Royal Prince": "Royal Prince Oak",
    "Quercus x bimundorum": "Two-worlds Oak",
    "Quercus x macdanielli": "Heritage Oak",
    "Quercus x warei": "Ware's Oak",
    "Rhamnus cathartica": "Common Buckthorn",
    "Rhamnus spp.": "Buckthorn species",
    "Rhus glabra": "Smooth Sumac",
    "Rhus spp.": "Sumac species",
    "Rhus typhina": "Staghorn Sumac",
    "Ribes x Pixwell": "Pixwell Gooseberry",
    "Robinia pseudoacacia": "Black Locust",
    "Salix alba": "White Willow",
    "Salix amygdaloides": "Peachleaf Willow",
    "Salix discolor": "Pussy Willow",
    "Salix matsudana": "Corkscrew Willow",
    "Salix nigra": "Black Willow",
    "Salix spp.": "Willow species",
    "Salix x Prairie Cascade": "Prairie Cascade Willow",
    "Salix x sepulcralis": "Weeping Willow",
    "Sorbus alnifolia": "Korean Mountain-ash",
    "Sorbus americana": "American Mountain-ash",
    "Sorbus aucuparia": "European Mountain-ash",
    "Sorbus decora": "Showy Mountain-ash",
    "Sorbus spp.": "Mountain-ash species",
    "Sorbus x hybrida": "Oakleaf Mountain-ash",
    "Styphnolobium japonicum": "Japanese Pagoda Tree",
    "Syringa pekinensis": "Peking Tree Lilac",
    "Syringa reticulata": "Japanese Tree Lilac",
    "Syringa spp.": "Lilac species",
    "Syringa vulgaris": "Common Lilac",
    "Taxodium distichum": "Bald Cypress",
    "Taxus baccata": "English Yew",
    "Taxus canadensis": "Canada Yew",
    "Taxus spp.": "Yew species",
    "Thuja occidentalis": "Northern White-cedar",
    "Tilia americana": "American Basswood",
    "Tilia cordata": "Littleleaf Linden",
    "Tilia spp.": "Linden species",
    "Tilia tomentosa": "Silver Linden",
    "Tilia x Harvest Gold": "Harvest Gold Linden",
    "Tilia x flavescens": "Dropmore Linden",
    "Tsuga canadensis": "Eastern Hemlock",
    "Tsuga spp.": "Hemlock species",
    "Ulmus americana": "American Elm",
    "Ulmus carpinifolia": "European Field Elm",
    "Ulmus davidiana": "David Elm",
    "Ulmus morton": "Morton Elm",
    "Ulmus parvifolia": "Chinese Elm",
    "Ulmus propinqua": "Harbin Elm",
    "Ulmus pumila": "Siberian Elm",
    "Ulmus rubra": "Slippery Elm",
    "Ulmus spp.": "Elm species",
    "Ulmus thomasii": "Rock Elm",
    "Ulmus x Cathedral": "Cathedral Elm",
    "Ulmus x Frontier": "Frontier Elm",
    "Ulmus x Homestead": "Homestead Elm",
    "Ulmus x Morton": "Accolade Elm",
    "Ulmus x Morton Glossy": "Triumph Elm",
    "Ulmus x Morton Plainsman": "Vanguard Elm",
    "Ulmus x Morton Red Tip": "Danada Charm Elm",
    "Ulmus x Morton Stalwart": "Commendation Elm",
    "Ulmus x New Horizon": "New Horizon Elm",
    "Ulmus x Patriot": "Patriot Elm",
    "Ulmus x Rebella": "Rebella Elm",
    "Ulmus x Regal": "Regal Elm",
    "Ulmus x hollandica": "Dutch Elm",
    "Ulmus x intermedia": "Hybrid Elm",
    "Viburnum lentago": "Nannyberry",
    "Zelkova serrata": "Japanese Zelkova",
    "Populus balsamifera": "Balsam Poplar",
    "Malus x Pinkspire": "Pinkspire Flowering Crabapple",
    "Acer miyabei": "Miyabe Maple",
    "Acer tataricum": "Tatarian Maple",
    "Malus x Velvet Pillar": "Velvet Pillar Flowering Crabapple",
    "Quercus x Clemons": "Heritage Oak",
    "Malus x Red Jewel": "Red Jewel Flowering Crabapple",
    "Malus x Red Baron": "Red Baron Flowering Crabapple",
    "Castanea spp.": "Chestnut species",
    "Malus x Purple Prince": "Purple Prince Flowering Crabapple",
    "Malus x Harvest Gold": "Harvest Gold Flowering Crabapple",
    "Malus x Thunderchild": "Thunderchild Flowering Crabapple",
    "Prunus bali": "Bali Cherry",
    "Prunus x cistena": "Purple-Leaf Sand Cherry",
    "Fraxinus quadrangulata": "Blue Ash",
    "Malus x Coralburst": "Coralburst Flowering Crabapple",
    "Tilia x mongolica": "Harvest Gold Linden",
    "Malus x Profusion": "Profusion Flowering Crabapple",
    "Malus x Jarmin": "Marilee Flowering Crabapple",
    "Malus x Lancelot": "Lancelot Flowering Crabapple",
    "Malus x adstringens": "Zumi Crabapple",
    "Corylus americana": "American Hazelnut",
    "Malus x Adirondack": "Adirondack Flowering Crabapple",
    "Phellodendron x His Majesty": "His Majesty Corktree",
    "Prunus pensylvanica": "Pin Cherry",
    "Populus balsamifera": "Balsam Poplar",
    "Thuja spp.": "Arborvitae species",
    "Salix babylonica": "Weeping Willow",
    "Malus sylvestris": "European Crabapple",
    "Quercus x heritage": "Heritage Oak",
    "Salix lutea": "Yellow Willow",
    "Corylus maxima": "Giant Filbert",
    "Prunus avium": "Sweet Cherry",
    "Magnolia grandiflora": "Southern Magnolia",
    "Betula pubescens": "Downy Birch",
    "Cotinus spp.": "Smoketree species",
    "Fraxinus excelsior": "European Ash",
    "Gossypium herbaceum": "Levant Cotton",
    "Cedrus deodara": "Deodar Cedar",
    "Buxus sempervirens": "Common Boxwood",
    "Arachis hypogaea": "Peanut",
    "Quercus x schuettei": "Schuette's Oak",
    "Maackia amurensis": "Amur Maackia",
    "Acer japonica": "Fullmoon Maple",
    "Ulmus hollandica": "Dutch Elm",
    "Lonicera spp.": "Honeysuckle species",
    "Tilia mongolica": "Mongolian Linden",
    "Zanthoxylum americanum": "Common Prickly-ash",
    "Ulmus patriot": "Patriot Elm",
    "Euonymus alatus": "Burning Bush",
    "Taxus cuspidata": "Japanese Yew",
    "Coffea arabica": "Arabian Coffee",
    "Castanea crenata": "Japanese Chestnut",
    "Cedrus atlantica": "Atlas Cedar",
    "Hydrangea paniculata": "Panicled Hydrangea",
    "Picea omorika": "Serbian Spruce",
    "Sassafras albidum": "Sassafras",
    "Malus x Centurion": "Centurion Crabapple",
    "Populus fremontii": "Fremont Cottonwood",
    "Pinus glabra": "Cedar Pine",
    "Picea rubens": "Red Spruce",
    "Quercus macdanielii": "Heritage Oak",
    "Populus tremula": "European Aspen",
    "Crataegus laevis": "Smooth Hawthorn",
    "Pinus rubra": "Red Pine",
    "Malus transitoria": "Cutleaf Crabapple",
    "Amelanchier grandidentata": "Large-toothed Serviceberry",
    "Amorpha fruticosa": "Desert False Indigo",
    "Cornus amomum": "Silky Dogwood",
    "Quercus americana": "White Oak",
    "Ilex verticillata": "Winterberry",
    "Malus x Ruby tears": "Ruby Tears Crabapple",
    "Viburnum spp.": "Viburnum species",
    "Corylus spp.": "Hazelnut species",
    "Acer griseum": "Paperbark Maple",
    "Alnus incana": "Speckled Alder",
    "Salix bebbiana": "Bebb's Willow",
    "Acer x Morton Glossy": "Triumph Maple",
    "Dirca palustris": "Eastern Leatherwood",
    "Sambucus canadensis": "American Elderberry",
    "Betula pumila": "Bog Birch",
    "Cornus americana": "Red-osier Dogwood",
    "Aronia melanocarpa": "Black Chokeberry",
    "Spiraea x vanhouttei": "Vanhoutte Spirea",
    "Quercus x Crimson Spire": "Crimson Spire Oak",
    "Picea strobus": "Eastern White Pine",
    "Cephalanthus occidentalis": "Buttonbush",
    "Viburnum trilobum": "Highbush Cranberry",
    "Salix lucida": "Shining Willow",
    "Rhamnus frangula": "Glossy Buckthorn",
    "Prunus tomentosa": "Nanking Cherry",
    "Prunus toka": "Toka Plum",
    "Quercus x Regal Prince": "Regal Prince Oak",
    "Pinus taeda": "Loblolly Pine",
    "Thuja plicata": "Western Redcedar",
    "Magnolia x soulangeana": "Saucer Magnolia",
    "Rhamnus purshiana": "Cascara",
    "Malus x Royalty": "Royalty Crabapple",
    "Betula x Crimson Frost": "Crimson Frost Birch",
    "Aesculus sylvatica": "Painted Buckeye",
    "Malus sargentii": "Sargent Crabapple",
    "Araucaria heterophylla": "Norfolk Island Pine",
    "Hydrangea spp.": "Hydrangea species",
    "Malus x Sutyzam": "Sugar Tyme Crabapple",
    "Acer buergerianum": "Trident Maple",
    "Malus x Indian Magic": "Indian Magic Crabapple",
    "Pinus sibirica": "Siberian Pine",
    "Malus x Velvetcole": "Velvet Pillar Crabapple",
    "Spiraea cantoniensis": "Reeves Spirea",
    "Cornus florida": "Flowering Dogwood",
    "Rhus aromatica": "Fragrant Sumac",
    "Quercus coccinea": "Scarlet Oak",
    "Quercus stellata": "Post Oak",
    "Malus pumila": "Common Apple",
    "Quercus shumardii": "Shumard Oak",
    "Euonymus spp.": "Euonymus species",
    "Malus floribunda": "Japanese Flowering Crabapple",
    "Prunus serrulata": "Japanese Flowering Cherry",
    "Rhus typhina": "Staghorn Sumac",
    "Lonicera canadensis": "American Fly Honeysuckle",
    "Acacia saligna": "Orange Wattle",
    "408469,Pseudotsuga macrocarpa": "Bigcone Douglas-fir",
    "Pinus balfouriana": "Foxtail Pine",
    "Caragana arborescens": "Siberian Peashrub",
    "Betula occidentalis": "Water Birch",
    "Salix purpurea": "Purpleosier Willow",
    "Cassia artemisioides": "Silver Cassia",
    "Syringa oblata": "Early Lilac",
    "Cedrus spp.": "Cedar species",
    "Nelumbo nucifera": "Sacred Lotus",
    "Abelia x grandiflora": "Glossy Abelia",
    "Ulmus x Sapporo Autumn Gold": "Sapporo Autumn Gold Elm",
    "Pinus lambertiana": "Sugar Pine",
    "Magnolia x Butterflies": "Butterflies Magnolia",
    "Abies sibirica": "Siberian Fir",
    "Crataegus laevigata": "English Hawthorn",
    "Malus x Starlite": "Starlite Crabapple",
    "Chionanthus virginicus": "White Fringetree",
    "Celastrus orbiculatus": "Oriental Bittersweet",
    "Spiraea spp.": "Spirea species",
    "Gleditsia spp.": "Honey Locust species",
    "Euonymus bungeana": "Winterberry Euonymus",
    "Acer spicatum": "Mountain Maple",
    "Betula x Royal Frost": "Royal Frost Birch",
    "Tamarix spp.": "Tamarisk species",
    "Malus x Sugar Tyme": "Sugar Tyme Crabapple",
    "Alnus rugosa": "Speckled Alder",
    "Amur maackia": "Amur Maackia",
    "Rhustyphina spp.": "Staghorn Sumac",
    "Pseudotsuga macrocarpa": "Bigcone Douglas-fir",
}
